### PR TITLE
Simplify composer.json

### PR DESCRIPTION
**Pull request by anavarre**
This improves readability.

### CODE REVIEW

**Comment by webbj74** [comment]
Is there a standard that you can point to where this convention is used? Questioning whether this makes things more readable...

**Comment by webbj74** [comment]
Also do the items in square braces still need quotes?

**Comment by anavarre** [comment]
> Is there a standard that you can point to where this convention is used?

There's no standard/best practice that I know of but [core does it this way](http://cgit.drupalcode.org/drupal/tree/composer.json#n35), which is why I think we should settle on a similar approach for consistency.

> Also do the items in square braces still need quotes?

Either way works. Core does keep them and GH doesn't seem happy that we've removed them, so perhaps this one IS a best practice.

**Comment by anavarre** [comment]
https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

Looks like the official docs do:

* Key value on the same line
* Quotes everywhere

**Comment by mariagwyn** [comment]
My original composer.json had everything on one line. Then, BLT came along and kept replacing/changing it b/c it was looking for an exact match to what IT had. So I modified my composer.json. But now that BLT has changed its method, this might not be a problem anymore. So, merging.

**Pull request merged**
